Repository min-gyoung/SlotIn, pull requests merged in 2025-06, with the labels that each got.

#7 TimeTableView
  SlotIn/Services/CalendarManager.swift
  SlotIn/ViewModels/TimeTableModel.swift
  SlotIn/Views/Home/TimeTableView.swift
  SlotIn/Views/Home/TimeTableViewModal.swift
Labels: ✨Feature

#8 feat: DetailInputView 구현
  SlotIn.xcodeproj/project.pbxproj
  SlotIn.xcodeproj/project.xcworkspace/xcuserdata/borayun.xcuserdatad/UserInterfaceState.xcuserstate
  SlotIn/Views/Home/DetailInputView.swift
  SlotIn/Views/Home/SelectTaskView.swift
  SlotIn/Views/Home/TimeTableView.swift
Labels: ✨Feature

#9 Conflict
  SlotIn.xcodeproj/project.pbxproj
  SlotIn.xcodeproj/project.xcworkspace/xcuserdata/air.xcuserdatad/UserInterfaceState.xcuserstate
  SlotIn/SlotInApp.swift
Labels: 🐛BugFix

#13 TimeTableView
  SlotIn/Views/Home/TimeTableView.swift
  SlotIn/Views/Home/TimeTableViewModal.swift
Labels: ✨Feature

#23 fix: TimeTableView에서 시작기한에서 부터 마감기한 전까지만 슬롯 선택할 수 있도록 수정
  SlotIn/Views/Home/TimeTableView.swift
Labels: ✨Feature

#14 chore: 수정 요청사항 반영
  SlotIn/Views/Home/DetailInputView.swift
  SlotIn/Views/Home/SelectTaskView.swift
Labels: ✨Feature, 🔨Refactor

#28 Feature/deadline
  SlotIn/Views/Home/DetailInputView.swift
  SlotIn/Views/Home/TimeTableView.swift
Labels: ✨Feature

#27 일정 변경 구현
  SlotIn/Views/Home/TimeTableViewModal.swift
Labels: ✨Feature

#30 chore: TaskView에 onDelete 추가
  SlotIn/Views/Home/SelectTaskView.swift
  SlotIn/Views/Task/TaskView.swift
Labels: ✨Feature

#29 Conflict Fix
  SlotIn.xcodeproj/project.xcworkspace/xcuserdata/air.xcuserdatad/UserInterfaceState.xcuserstate
  SlotIn/Views/Task/TaskDetailView.swift
  SlotIn/Views/Task/TaskView.swift
Labels: 🐛BugFix

#36 fix: Conflict fix
  SlotIn/Views/Home/DetailInputView.swift
Labels: 🐛BugFix

#39 feat: SelectedTaskCalendarView UI구현
  SlotIn/Views/Home/SelectedTaskCalendarView.swift
Labels: ✨Feature

#40 SelectedTaskListView 구현
  SlotIn/Services/CalendarManager.swift
  SlotIn/Views/Home/SelectedTaskListView.swift
  SlotIn/Views/Task/TaskView.swift
Labels: ✨Feature
